
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username: <change-it>
    password: <change-it>

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "<change-it>"
  valid-duration: 3600 # in second
  refreshable-duration: 36000 # in seconds