
server:
  port: 8080
  servlet:
    context-path: /identity

spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/identity_service"
    driverClassName: "com.mysql.cj.jdbc.Driver"
    username:
    password: 

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true